#! /bin/bash

set -e
set -u

# MAKE SURE THIS IS SSL!
URL="https://raw.github.com/puppetlabs/puppetlabs-sshkeys/master/templates/ssh/authorized_keys"

if [[ `uname` == CYGWIN* ]]
then
  OWNER="Administrator"
  GROUP="None"
  SSH_HOME=~Administrator/.ssh/
else
  OWNER="0"
  GROUP="0"
  SSH_HOME=~root/.ssh/
fi

if which curl 2>&1 >/dev/null
then
  GET="curl -o - ${URL}"
else
  GET="wget -q -O - ${URL}"
fi

if ! [[ -d $SSH_HOME ]]
then
  mkdir $SSH_HOME
  chmod 700 $SSH_HOME
  chown $OWNER:$GROUP $SSH_HOME
fi

# Make sure there is no temporary file
if [[ -f $SSH_HOME/authorized_keys.tmp ]]
then
  rm -f $SSH_HOME/authorized_keys.tmp
fi

# This should be gone now.
if ! [[ -f $SSH_HOME/authorized_keys.tmp ]]
then
  touch $SSH_HOME/authorized_keys.tmp
  chmod 644 $SSH_HOME/authorized_keys.tmp
  chown $OWNER:$GROUP $SSH_HOME/authorized_keys.tmp
fi

# Download the file.  If this fails the script will abort since we're set -e
$GET > $SSH_HOME/authorized_keys.tmp

# Now move the file into place.  POSIX rename is atomic.
mv -f $SSH_HOME/authorized_keys.tmp $SSH_HOME/authorized_keys
